package controller;

import static controller.Errs.same;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assumptions.assumeFalse;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import javax.imageio.ImageIO;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import fileAssociations.FileAssociations;
import fileAssociations.Icon;
import fileAssociations.LinuxAssociations;
import tools.Fs;

/// FileAssociations.reconcile on Linux, against a desktop made of the folders of a test.
final class LinuxAssociationsTest{
  private static final String identity= "fearlessManaged0_001";
  private static final Path command= Path.of("/opt/fearlessManaged0_001/bin/fearlessManaged0_001");
  @TempDir Path root;
  private Path home;
  private Path sys;
  private final List<List<String>> ran= new ArrayList<>();
  private Function<String,String> env;
  private BiConsumer<List<String>,Function<String,RuntimeException>> run;
  @BeforeEach void desktop(){
    assumeTrue(Fs.isLinux());
    home= root.resolve("home");
    sys= root.resolve("sys");
    env= LinuxAssociations.env;
    run= LinuxAssociations.run;
    var vars= Map.of("XDG_DATA_HOME",home.toString(),"XDG_DATA_DIRS",sys.toString(),
      "XDG_CONFIG_HOME",root.resolve("config").toString(),"XDG_CONFIG_DIRS",root.resolve("etc").toString(),"XDG_CURRENT_DESKTOP","");
    LinuxAssociations.env= vars::get;
    LinuxAssociations.run= (cmd,_)->ran.add(cmd);
    Fs.writeUtf8(sys.resolve("mime").resolve("globs2"),"""
      # This file was automatically generated by the
      # update-mime-database command. DO NOT EDIT!
      80:text/html:*.htm
      80:text/html:*.html
      50:application/xhtml+xml:*.htm
      50:text/plain:*.txt
      50:text/x-bar:*.BAR
      50:text/x-csrc:*.c:cs
      50:text/x-c++src:*.C:cs
      """);
  }
  @AfterEach void restore(){
    if (env == null){ return; }
    LinuxAssociations.env= env;
    LinuxAssociations.run= run;
  }
  private Path icon(int rgb){
    var file= root.resolve("in").resolve(Integer.toHexString(rgb)+".png");
    var img= new BufferedImage(64,64,BufferedImage.TYPE_INT_RGB);
    var g= img.createGraphics();
    g.setColor(new Color(rgb));
    g.fillRect(0,0,64,64);
    g.dispose();
    Fs.ensureDir(file.getParent());
    Fs.ofV(()->ImageIO.write(img,"png",file.toFile()));
    return file;
  }
  private void reconcile(String... extensions){
    var program= icon(0x123456);
    var icons= Stream.of(extensions).map(e->{ var png= icon(e.hashCode() & 0xffffff); return new Icon(e,png,png); }).toList();
    FileAssociations.reconcile(identity,Association.belongsToFamily,command,icons,program,program,
      s->new IllegalStateException("ambiguous "+s),
      s->new IllegalStateException("userLocked "+s),
      s->new IllegalStateException("notOurs "+s),
      s->new IllegalStateException("notWritable "+s),
      s->new IllegalStateException("halfDone "+s));
  }
  private String refused(String... extensions){ return assertThrows(IllegalStateException.class,()->reconcile(extensions)).getMessage(); }
  private Path mimetypes(){ return home.resolve("icons").resolve("hicolor").resolve("256x256").resolve("mimetypes"); }
  private Path appIcon(){ return home.resolve("icons").resolve("hicolor").resolve("256x256").resolve("apps").resolve(identity+".png"); }
  private Path desktopFile(){ return home.resolve("applications").resolve(identity+".desktop"); }
  private Path packageFile(){ return home.resolve("mime").resolve("packages").resolve(identity+".xml"); }
  private String mimeTypes(){ return Fs.readUtf8(desktopFile()).lines().filter(l->l.startsWith("MimeType=")).findFirst().orElseThrow(); }
  private List<String> icons(){
    if (!Files.isDirectory(mimetypes())){ return List.of(); }
    return Fs.of(()->{ try(var s= Files.list(mimetypes())){ return s.map(p->p.getFileName().toString()).sorted().toList(); }});
  }
  private List<List<String>> rebuilt(){
    return List.of(List.of("update-mime-database",home.resolve("mime").toString()),List.of("update-desktop-database",home.resolve("applications").toString()));
  }
  private String mimeInfo(String... types){
    return """
      <?xml version="1.0" encoding="UTF-8"?>
      <mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
      """+Stream.of(types).map(t->"  <mime-type type=\"application/x-fearless"+t+"<icon name=\"fearlessManaged0_001-[###]\"/></mime-type>\n").collect(Collectors.joining())+"</mime-info>\n";
  }
  @Test void aSystemExtensionGetsATypeOfItsOwnBelowEveryTypeTheSystemGivesIt(){
    reconcile(".htm");
    same(mimeInfo("-htm\"><comment>fearlessManaged0_001</comment><glob pattern=\"*.htm\" weight=\"100\"/><sub-class-of type=\"text/html\"/><sub-class-of type=\"application/xhtml+xml\"/>"),Fs.readUtf8(packageFile()));
    assertEquals("MimeType=application/x-fearless-htm;",mimeTypes());
    assertEquals(1,icons().size());
    assertTrue(Files.isRegularFile(appIcon()));
    assertEquals(rebuilt(),ran);
  }
  @Test void theProgramsOpeningTheSystemTypesDoNotHoldASystemExtension(){
    Fs.writeUtf8(sys.resolve("applications").resolve("browser.desktop"),"[Desktop Entry]\nMimeType=text/html;application/xhtml+xml;\n");
    Fs.writeUtf8(root.resolve("config").resolve("mimeapps.list"),"[Default Applications]\ntext/html=browser.desktop\n[Added Associations]\ntext/html=browser.desktop;\n");
    reconcile(".htm");
    assertEquals("MimeType=application/x-fearless-htm;",mimeTypes());
  }
  @Test void aDefaultApplicationOfAnotherProgramForTheTypeOfASystemExtensionLocksIt(){
    Fs.writeUtf8(root.resolve("config").resolve("mimeapps.list"),"[Default Applications]\napplication/x-fearless-htm=browser.desktop\napplication/x-fearless-txt="+identity+".desktop\n"
      +"[Added Associations]\napplication/x-fearless-c=editor.desktop;\n");
    Fs.writeUtf8(sys.resolve("applications").resolve("editor.desktop"),"[Desktop Entry]\nMimeType=application/x-fearless-c;\n");
    assertEquals("userLocked [.htm]",refused(".c",".htm",".txt"));
    assertFalse(Files.exists(home));
    assertEquals(List.of(),ran);
  }
  @Test void aFearlessExtensionAnotherPackageGivesATypeIsNotOurs(){
    sysMime("globs2","50:application/x-other:*.ffile042\n50:application/x-wide:*.ffile04[0-9]\n50:application/x-near:*.ffile043\n");
    assertEquals("notOurs {.ffile042=[application/x-other, application/x-wide]}",refused(".htm",".ffile042"));
    assertFalse(Files.exists(home));
  }
  @Test void aFearlessExtensionWhoseTypeAnotherProgramListsOrIsAssociatedWithIsNotOurs(){
    Fs.writeUtf8(sys.resolve("applications").resolve("vim.desktop"),"[Desktop Entry]\nMimeType=application/x-fearless-ffile042;\n");
    Fs.writeUtf8(root.resolve("config").resolve("mimeapps.list"),"[Added Associations]\napplication/x-fearless-fapp001=other.desktop;\n[Removed Associations]\napplication/x-fearless-ffile042=gone.desktop;\n");
    assertEquals("notOurs {.ffile042=[vim], .fapp001=[other]}",refused(".ffile042",".fapp001"));
    assertFalse(Files.exists(home));
  }
  @Test void fearlessKeepsItsTypeAndIsHeldOnlyByTheProgramsListingItOrChosenForIt(){
    sysMime("globs2","50:application/x-other:*.fearless\n");
    Fs.writeUtf8(root.resolve("config").resolve("mimeapps.list"),"[Added Associations]\napplication/x-fearless=other.desktop;\n");
    reconcile(".fearless");
    same(mimeInfo("\"><comment>fearlessManaged0_001</comment><glob pattern=\"*.fearless\" weight=\"100\"/>"),Fs.readUtf8(packageFile()));
    assertEquals("MimeType=application/x-fearless;",mimeTypes());
    Fs.writeUtf8(sys.resolve("applications").resolve("vim.desktop"),"[Desktop Entry]\nMimeType=application/x-fearless;\n");
    Fs.writeUtf8(root.resolve("etc").resolve("mimeapps.list"),"[Default Applications]\napplication/x-fearless=editor.desktop\n");
    assertEquals("notOurs {.fearless=[vim, editor]}",refused(".fearless"));
  }
  @Test void releasingAnExtensionLeavesThePackageWithoutIt(){
    reconcile(".fearless",".htm",".ffile042");
    ran.clear();
    reconcile(".fearless",".ffile042");
    same(mimeInfo(
      "\"><comment>fearlessManaged0_001</comment><glob pattern=\"*.fearless\" weight=\"100\"/>",
      "-ffile042\"><comment>fearlessManaged0_001</comment><glob pattern=\"*.ffile042\" weight=\"100\"/>"),Fs.readUtf8(packageFile()));
    assertEquals("MimeType=application/x-fearless;application/x-fearless-ffile042;",mimeTypes());
    assertEquals(2,icons().size());
    assertEquals(rebuilt(),ran);
  }
  @Test void aGlobIgnoresCaseUnlessItsFlagSaysOtherwise(){
    reconcile(".bar",".c");
    same(mimeInfo(
      "-bar\"><comment>fearlessManaged0_001</comment><glob pattern=\"*.bar\" weight=\"100\"/><sub-class-of type=\"text/x-bar\"/>",
      "-c\"><comment>fearlessManaged0_001</comment><glob pattern=\"*.c\" weight=\"100\"/><sub-class-of type=\"text/x-csrc\"/>"),Fs.readUtf8(packageFile()));
  }
  @Test void theTypesTheFamilyDeclaredAreNotSystemTypes(){
    var old= "fearlessManaged0_000";
    Fs.writeUtf8(home.resolve("mime").resolve("globs2"),"100:application/x-fearless-ffile001:*.ffile001\n");
    Fs.writeUtf8(home.resolve("mime").resolve("packages").resolve(old+".xml"),
      "  <mime-type type=\"application/x-fearless-ffile001\"><comment>x</comment><glob pattern=\"*.ffile001\" weight=\"100\"/><icon name=\""+old+"-1\"/></mime-type>\n");
    Fs.writeUtf8(home.resolve("applications").resolve(old+".desktop"),"[Desktop Entry]\nMimeType=application/x-fearless-ffile001;\n");
    Fs.writeUtf8(mimetypes().resolve(old+"-1.png"),"");
    reconcile(".ffile001");
    assertEquals("MimeType=application/x-fearless-ffile001;",mimeTypes());
    assertFalse(Files.exists(home.resolve("mime").resolve("packages").resolve(old+".xml")));
    assertFalse(Files.exists(mimetypes().resolve(old+"-1.png")));
  }
  private void sysMime(String file, String text){
    var path= sys.resolve("mime").resolve(file);
    Fs.writeUtf8(path,(Files.exists(path) ? Fs.readUtf8(path) : "")+text);
  }
  @Test void aGlobOfTheDesktopFolderNoPackageThereNamesIsStale(){
    Fs.writeUtf8(home.resolve("mime").resolve("globs2"),"100:application/x-gone:*.ffile001\n50:text/x-qux:*.qux\n");
    Fs.writeUtf8(home.resolve("mime").resolve("packages").resolve("other.xml"),"<mime-type type='text/x-qux'><glob pattern='*.qux'/></mime-type>\n");
    reconcile(".ffile001",".qux");
    same(mimeInfo(
      "-ffile001\"><comment>fearlessManaged0_001</comment><glob pattern=\"*.ffile001\" weight=\"100\"/>",
      "-qux\"><comment>fearlessManaged0_001</comment><glob pattern=\"*.qux\" weight=\"100\"/><sub-class-of type=\"text/x-qux\"/>"),Fs.readUtf8(packageFile()));
  }
  @Test void theDatabaseRebuiltFromThePackageChangesNothing(){
    reconcile(".fearless",".htm");
    Fs.writeUtf8(home.resolve("mime").resolve("globs2"),"100:application/x-fearless:*.fearless\n100:application/x-fearless-htm:*.htm\n");
    Fs.writeUtf8(home.resolve("mime").resolve("subclasses"),"application/x-fearless-htm text/html\napplication/x-fearless-htm application/xhtml+xml\n");
    ran.clear();
    reconcile(".fearless",".htm");
    assertEquals(List.of(),ran);
  }
  @Test void anUnwritableIconFolderIsRefusedBeforeWritingAnything(){
    Fs.writeUtf8(mimetypes().resolve(identity+"-0123abc.png"),"");
    assertTrue(mimetypes().toFile().setWritable(false));
    try{
      assumeFalse(Files.isWritable(mimetypes()));
      assertEquals("notWritable "+mimetypes(),refused(".ffile001"));
    }
    finally{ mimetypes().toFile().setWritable(true); }
    assertTrue(Files.exists(mimetypes().resolve(identity+"-0123abc.png")));
    assertFalse(Files.exists(desktopFile()));
    assertEquals(List.of(),ran);
  }
  @Test void removingEveryIdentityRemovesTheIconsOfIdentitiesAlreadyGone(){
    Fs.writeUtf8(mimetypes().resolve("fearlessBin0_001-a52baa.png"),"");
    Fs.writeUtf8(mimetypes().resolve("fearlessBin0_001.png"),"");
    Fs.writeUtf8(mimetypes().resolve("other-a52baa.png"),"");
    Fs.writeUtf8(appIcon().resolveSibling("fearlessBin0_001.png"),"");
    Fs.writeUtf8(appIcon().resolveSibling("other.png"),"");
    FileAssociations.eradicateAll(Association.belongsToFamily,IllegalStateException::new);
    assertEquals(List.of("fearlessBin0_001.png","other-a52baa.png"),icons());
    assertEquals(List.of(appIcon().resolveSibling("other.png")),Fs.of(()->{ try(var s= Files.list(appIcon().getParent())){ return s.toList(); }}));
    assertEquals(List.of(),ran);
  }
  @Test void eachReconcileLeavesOnlyTheIconsItWantsOfItsIdentity(){
    reconcile(".ffile001",".htm");
    var wanted= icons();
    Fs.writeUtf8(mimetypes().resolve(identity+"-0123abc.png"),"");
    Fs.writeUtf8(mimetypes().resolve(identity+"x-0123abc.png"),"");
    Fs.writeUtf8(mimetypes().resolve(identity+"-other-0123abc.png"),"");
    Fs.writeUtf8(mimetypes().resolve(identity+"-0123ABC.png"),"");
    ran.clear();
    reconcile(".ffile001",".htm");
    assertEquals(rebuilt(),ran);
    var others= List.of(identity+"-0123ABC.png",identity+"-other-0123abc.png",identity+"x-0123abc.png");
    assertEquals(Stream.concat(wanted.stream(),others.stream()).sorted().toList(),icons());
    ran.clear();
    reconcile(".ffile001",".htm");
    assertEquals(List.of(),ran);
    reconcile(".ffile001");
    assertEquals(1,icons().stream().filter(n->n.matches(identity+"-[0-9a-f]+\\.png")).count());
  }
  @Test void removingTheIdentityRemovesAllItsFiles(){
    reconcile(".ffile001",".htm");
    Fs.writeUtf8(mimetypes().resolve(identity+"-0123abc.png"),"");
    Fs.writeUtf8(mimetypes().resolve("other-0123abc.png"),"");
    ran.clear();
    FileAssociations.eradicateAll(Association.belongsToFamily,IllegalStateException::new);
    assertEquals(rebuilt(),ran);
    assertEquals(List.of("other-0123abc.png"),icons());
    assertFalse(Files.exists(appIcon()));
    assertFalse(Files.exists(desktopFile()));
    assertFalse(Files.exists(packageFile()));
  }
  @Test void noExtensionsLeavesNoFileOfTheIdentity(){
    reconcile(".ffile001");
    reconcile();
    assertEquals(List.of(),icons());
    assertFalse(Files.exists(appIcon()));
    assertFalse(Files.exists(desktopFile()));
    ran.clear();
    reconcile();
    assertEquals(List.of(),ran);
  }
}
