package controller;

import static controller.Errs.same;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assumptions.assumeFalse;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;
import java.util.stream.Stream;

import javax.imageio.ImageIO;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import fileAssociations.FileAssociations;
import fileAssociations.Icon;
import fileAssociations.LinuxAssociations;
import tools.Fs;

/// FileAssociations.reconcile on Linux, against a desktop made of the folders of a test.
final class LinuxAssociationsTest{
  private static final String identity= "fearlessManaged0_001";
  private static final Path command= Path.of("/opt/fearlessManaged0_001/bin/fearlessManaged0_001");
  @TempDir Path root;
  private Path home;
  private Path sys;
  private final List<List<String>> ran= new ArrayList<>();
  private Function<String,String> env;
  private BiConsumer<List<String>,Function<String,RuntimeException>> run;
  @BeforeEach void desktop(){
    assumeTrue(Fs.isLinux());
    home= root.resolve("home");
    sys= root.resolve("sys");
    env= LinuxAssociations.env;
    run= LinuxAssociations.run;
    var vars= Map.of("XDG_DATA_HOME",home.toString(),"XDG_DATA_DIRS",sys.toString(),
      "XDG_CONFIG_HOME",root.resolve("config").toString(),"XDG_CONFIG_DIRS",root.resolve("etc").toString(),"XDG_CURRENT_DESKTOP","");
    LinuxAssociations.env= vars::get;
    LinuxAssociations.run= (cmd,_)->ran.add(cmd);
    Fs.writeUtf8(sys.resolve("mime").resolve("globs2"),"""
      # This file was automatically generated by the
      # update-mime-database command. DO NOT EDIT!
      50:text/plain:*.txt
      50:text/plain:*.asc
      50:text/plain:*,v
      50:text/x-foo:*.foo
      50:text/x-bar:*.BAR
      50:text/x-csrc:*.c:cs
      50:text/x-c++src:*.C:cs
      50:text/x-c++src:*.cpp
      50:text/x-gone:*.gone
      50:text/x-gone:*.other
      """);
  }
  @AfterEach void restore(){
    if (env == null){ return; }
    LinuxAssociations.env= env;
    LinuxAssociations.run= run;
  }
  private Path icon(int rgb){
    var file= root.resolve("in").resolve(Integer.toHexString(rgb)+".png");
    var img= new BufferedImage(64,64,BufferedImage.TYPE_INT_RGB);
    var g= img.createGraphics();
    g.setColor(new Color(rgb));
    g.fillRect(0,0,64,64);
    g.dispose();
    Fs.ensureDir(file.getParent());
    Fs.ofV(()->ImageIO.write(img,"png",file.toFile()));
    return file;
  }
  private void reconcile(String... extensions){
    var program= icon(0x123456);
    var icons= Stream.of(extensions).map(e->{ var png= icon(e.hashCode() & 0xffffff); return new Icon(e,png,png); }).toList();
    FileAssociations.reconcile(identity,Association.belongsToFamily,command,icons,program,program,
      s->new IllegalStateException("ambiguous "+s),
      s->new IllegalStateException("userLocked "+s),
      s->new IllegalStateException("sharedType "+s),
      s->new IllegalStateException("notOurs "+s),
      s->new IllegalStateException("notWritable "+s),
      s->new IllegalStateException("halfDone "+s));
  }
  private String refused(String... extensions){ return assertThrows(IllegalStateException.class,()->reconcile(extensions)).getMessage(); }
  private Path mimetypes(){ return home.resolve("icons").resolve("hicolor").resolve("256x256").resolve("mimetypes"); }
  private Path appIcon(){ return home.resolve("icons").resolve("hicolor").resolve("256x256").resolve("apps").resolve(identity+".png"); }
  private Path desktopFile(){ return home.resolve("applications").resolve(identity+".desktop"); }
  private Path packageFile(){ return home.resolve("mime").resolve("packages").resolve(identity+".xml"); }
  private String mimeTypes(){ return Fs.readUtf8(desktopFile()).lines().filter(l->l.startsWith("MimeType=")).findFirst().orElseThrow(); }
  private List<String> icons(){
    if (!Files.isDirectory(mimetypes())){ return List.of(); }
    return Fs.of(()->{ try(var s= Files.list(mimetypes())){ return s.map(p->p.getFileName().toString()).sorted().toList(); }});
  }
  private List<List<String>> rebuilt(){
    return List.of(List.of("update-mime-database",home.resolve("mime").toString()),List.of("update-desktop-database",home.resolve("applications").toString()));
  }
  @Test void anExtensionNoTypeHasGetsATypeOfItsOwn(){
    reconcile(".zork");
    same("""
      <?xml version="1.0" encoding="UTF-8"?>
      <mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
        <mime-type type="application/x-zork"><comment>fearlessManaged0_001</comment><glob pattern="*.zork" weight="100"/><icon name="fearlessManaged0_001-[###]"/></mime-type>
      </mime-info>
      """,Fs.readUtf8(packageFile()));
    assertEquals("MimeType=application/x-zork;",mimeTypes());
    assertEquals(1,icons().size());
    assertTrue(Files.isRegularFile(appIcon()));
    assertEquals(rebuilt(),ran);
  }
  @Test void anExtensionWithATypeOnlyGivesThatTypeItsIcon(){
    reconcile(".zork",".foo");
    same("""
      <?xml version="1.0" encoding="UTF-8"?>
      <mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
        <mime-type type="application/x-zork"><comment>fearlessManaged0_001</comment><glob pattern="*.zork" weight="100"/><icon name="fearlessManaged0_001-[###]"/></mime-type>
        <mime-type type="text/x-foo"><icon name="fearlessManaged0_001-[###]"/></mime-type>
      </mime-info>
      """,Fs.readUtf8(packageFile()));
    assertEquals("MimeType=application/x-zork;text/x-foo;",mimeTypes());
    assertEquals(2,icons().size());
  }
  @Test void aTypeOtherFileNamesShareIsRefusedBeforeWritingAnything(){
    assertEquals("sharedType {.txt=text/plain=[*.asc, *,v], .gone=text/x-gone=[*.other]}",refused(".foo",".txt",".gone"));
    assertFalse(Files.exists(home));
    assertEquals(List.of(),ran);
  }
  @Test void aGlobIgnoresCaseUnlessItsFlagSaysOtherwise(){
    reconcile(".bar",".c");
    assertEquals("MimeType=text/x-bar;text/x-csrc;",mimeTypes());
  }
  @Test void theProgramsOpeningTheTypeOfAnExtensionHoldIt(){
    Fs.writeUtf8(sys.resolve("applications").resolve("vim.desktop"),"[Desktop Entry]\nMimeType=text/x-foo;text/x-csrc;\n");
    assertEquals("notOurs {.foo=[vim]}",refused(".zork",".foo"));
    assertFalse(Files.exists(home));
  }
  @Test void theTypesTheFamilyDeclaredAreNotKnownTypes(){
    var old= "fearlessManaged0_000";
    Fs.writeUtf8(home.resolve("mime").resolve("globs2"),"100:application/x-zork:*.zork\n");
    Fs.writeUtf8(home.resolve("mime").resolve("packages").resolve(old+".xml"),
      "  <mime-type type=\"application/x-zork\"><comment>x</comment><glob pattern=\"*.zork\" weight=\"100\"/><icon name=\""+old+"-1\"/></mime-type>\n"
      +"  <mime-type type=\"text/x-foo\"><icon name=\""+old+"-2\"/></mime-type>\n");
    Fs.writeUtf8(home.resolve("applications").resolve(old+".desktop"),"[Desktop Entry]\nMimeType=application/x-zork;text/x-foo;\n");
    Fs.writeUtf8(mimetypes().resolve(old+"-1.png"),"");
    reconcile(".zork",".foo");
    assertEquals("MimeType=application/x-zork;text/x-foo;",mimeTypes());
    assertFalse(Files.exists(home.resolve("mime").resolve("packages").resolve(old+".xml")));
    assertFalse(Files.exists(mimetypes().resolve(old+"-1.png")));
  }
  private void sysMime(String file, String text){
    var path= sys.resolve("mime").resolve(file);
    Fs.writeUtf8(path,(Files.exists(path) ? Fs.readUtf8(path) : "")+text);
  }
  @Test void aTypeTheFamilyDeclaredIsKnownWhereAnotherFolderDeclaresIt(){
    Fs.writeUtf8(home.resolve("mime").resolve("globs2"),"100:application/x-zork:*.zork\n");
    Fs.writeUtf8(home.resolve("mime").resolve("packages").resolve("fearlessManaged0_000.xml"),
      "  <mime-type type=\"application/x-zork\"><comment>x</comment><glob pattern=\"*.zork\" weight=\"100\"/><icon name=\"x\"/></mime-type>\n");
    sysMime("globs2","50:application/x-zork:*.zork\n50:application/x-zork:*.zrk\n");
    assertEquals("sharedType {.zork=application/x-zork=[*.zrk]}",refused(".zork"));
  }
  @Test void aGlobOfTheDesktopFolderNoPackageThereNamesIsStale(){
    Fs.writeUtf8(home.resolve("mime").resolve("globs2"),"100:application/x-zork:*.zork\n50:text/x-qux:*.qux\n");
    Fs.writeUtf8(home.resolve("mime").resolve("types"),"application/x-zork\ntext/x-qux\n");
    Fs.writeUtf8(home.resolve("mime").resolve("packages").resolve("other.xml"),"<mime-type type='text/x-qux'><glob pattern='*.qux'/></mime-type>\n");
    reconcile(".zork",".qux");
    same("""
      <?xml version="1.0" encoding="UTF-8"?>
      <mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
        <mime-type type="application/x-zork"><comment>fearlessManaged0_001</comment><glob pattern="*.zork" weight="100"/><icon name="fearlessManaged0_001-[###]"/></mime-type>
        <mime-type type="text/x-qux"><icon name="fearlessManaged0_001-[###]"/></mime-type>
      </mime-info>
      """,Fs.readUtf8(packageFile()));
  }
  @Test void theDatabaseRebuiltFromThePackageChangesNothing(){
    reconcile(".fearless",".foo");
    Fs.writeUtf8(home.resolve("mime").resolve("globs2"),"100:application/x-fearless:*.fearless\n");
    Fs.writeUtf8(home.resolve("mime").resolve("types"),"application/x-fearless\ntext/x-foo\n");
    ran.clear();
    reconcile(".fearless",".foo");
    assertEquals(List.of(),ran);
  }
  @Test void aTypeBelowTheTypeOfAnExtensionSharesIt(){
    sysMime("globs2","50:text/x-foo-dialect:*.food\n");
    sysMime("subclasses","text/x-foo-dialect text/x-foo\n");
    assertEquals("sharedType {.foo=text/x-foo=[*.food]}",refused(".foo"));
  }
  @Test void anExtensionWhoseTypeNameIsTakenIsShared(){
    sysMime("globs2","50:text/x-quux:*.quux\n");
    sysMime("types","application/x-executable\ntext/x-quux\n");
    sysMime("aliases","application/x-qq text/x-quux\n");
    assertEquals("sharedType {.executable=application/x-executable=[], .qq=text/x-quux=[*.quux]}",refused(".executable",".zork",".qq"));
    assertFalse(Files.exists(home));
  }
  @Test void theProgramsOpeningATypeAboveTheTypeOfAnExtensionHoldIt(){
    sysMime("subclasses","text/x-foo text/x-base\ntext/x-base text/plain\n");
    Fs.writeUtf8(sys.resolve("applications").resolve("editor.desktop"),"[Desktop Entry]\nMimeType=text/plain;\n");
    assertEquals("notOurs {.foo=[editor]}",refused(".foo"));
  }
  @Test void theProgramsNamingAnAliasOfTheTypeHoldIt(){
    sysMime("aliases","text/x-foo-old text/x-foo\n");
    Fs.writeUtf8(sys.resolve("applications").resolve("vim.desktop"),"[Desktop Entry]\nMimeType=text/x-foo-old;\n");
    Fs.writeUtf8(root.resolve("etc").resolve("mimeapps.list"),"[Default Applications]\ntext/x-foo-old=other.desktop\n");
    assertEquals("notOurs {.foo=[vim, other]}",refused(".foo"));
  }
  @Test void theAddedAssociationsHoldTheType(){
    Fs.writeUtf8(root.resolve("config").resolve("mimeapps.list"),
      "[Default Applications]\ntext/x-bar=a.desktop\n[Added Associations]\ntext/x-foo=b.desktop;c.desktop;\n[Removed Associations]\ntext/x-foo=d.desktop;\n");
    Fs.writeUtf8(home.resolve("applications").resolve("mimeapps.list"),"[Default Applications]\ntext/x-foo=e.desktop\n[Added Associations]\ntext/x-foo=f.desktop\n");
    assertEquals("notOurs {.foo=[b, c, e, f]}",refused(".foo"));
    assertFalse(Files.exists(desktopFile()));
  }
  @Test void anUnwritableIconFolderIsRefusedBeforeWritingAnything(){
    Fs.writeUtf8(mimetypes().resolve(identity+"-0123abc.png"),"");
    assertTrue(mimetypes().toFile().setWritable(false));
    try{
      assumeFalse(Files.isWritable(mimetypes()));
      assertEquals("notWritable "+mimetypes(),refused(".zork"));
    }
    finally{ mimetypes().toFile().setWritable(true); }
    assertTrue(Files.exists(mimetypes().resolve(identity+"-0123abc.png")));
    assertFalse(Files.exists(desktopFile()));
    assertEquals(List.of(),ran);
  }
  @Test void removingEveryIdentityRemovesTheIconsOfIdentitiesAlreadyGone(){
    Fs.writeUtf8(mimetypes().resolve("fearlessBin0_001-a52baa.png"),"");
    Fs.writeUtf8(mimetypes().resolve("fearlessBin0_001.png"),"");
    Fs.writeUtf8(mimetypes().resolve("other-a52baa.png"),"");
    Fs.writeUtf8(appIcon().resolveSibling("fearlessBin0_001.png"),"");
    Fs.writeUtf8(appIcon().resolveSibling("other.png"),"");
    FileAssociations.eradicateAll(Association.belongsToFamily,IllegalStateException::new);
    assertEquals(List.of("fearlessBin0_001.png","other-a52baa.png"),icons());
    assertEquals(List.of(appIcon().resolveSibling("other.png")),Fs.of(()->{ try(var s= Files.list(appIcon().getParent())){ return s.toList(); }}));
    assertEquals(List.of(),ran);
  }
  @Test void eachReconcileLeavesOnlyTheIconsItWantsOfItsIdentity(){
    reconcile(".zork",".foo");
    var wanted= icons();
    Fs.writeUtf8(mimetypes().resolve(identity+"-0123abc.png"),"");
    Fs.writeUtf8(mimetypes().resolve(identity+"x-0123abc.png"),"");
    Fs.writeUtf8(mimetypes().resolve(identity+"-other-0123abc.png"),"");
    Fs.writeUtf8(mimetypes().resolve(identity+"-0123ABC.png"),"");
    ran.clear();
    reconcile(".zork",".foo");
    assertEquals(rebuilt(),ran);
    var others= List.of(identity+"-0123ABC.png",identity+"-other-0123abc.png",identity+"x-0123abc.png");
    assertEquals(Stream.concat(wanted.stream(),others.stream()).sorted().toList(),icons());
    ran.clear();
    reconcile(".zork",".foo");
    assertEquals(List.of(),ran);
    reconcile(".zork");
    assertEquals(1,icons().stream().filter(n->n.matches(identity+"-[0-9a-f]+\\.png")).count());
  }
  @Test void removingTheIdentityRemovesAllItsFiles(){
    reconcile(".zork",".foo");
    Fs.writeUtf8(mimetypes().resolve(identity+"-0123abc.png"),"");
    Fs.writeUtf8(mimetypes().resolve("other-0123abc.png"),"");
    ran.clear();
    FileAssociations.eradicateAll(Association.belongsToFamily,IllegalStateException::new);
    assertEquals(rebuilt(),ran);
    assertEquals(List.of("other-0123abc.png"),icons());
    assertFalse(Files.exists(appIcon()));
    assertFalse(Files.exists(desktopFile()));
    assertFalse(Files.exists(packageFile()));
  }
  @Test void noExtensionsLeavesNoFileOfTheIdentity(){
    reconcile(".zork");
    reconcile();
    assertEquals(List.of(),icons());
    assertFalse(Files.exists(appIcon()));
    assertFalse(Files.exists(desktopFile()));
    ran.clear();
    reconcile();
    assertEquals(List.of(),ran);
  }
}
