package agentTools;

import java.util.List;

final class ClearOutputTest extends ManagerTest{
  final Action appsShown= action("appsShown",
    on("fedora_cosmic",()->waitUntilTime(val(2000))),
    on("ubuntu_gnome",()->waitUntilTime(val(2000))),
    on("debian_gnome_x11",()->waitUntilTime(val(2000))),
    on("fedora_gnome",()->waitUntilTime(val(2000))),
    on("xubuntu_xfce",()->waitUntilTime(val(2000))),
    on("debian_cinnamon",()->waitUntilTime(val(2000))),
    on("debian_mate",()->waitUntilTime(val(2000))),
    on("lubuntu_lxqt",()->waitUntilTime(val(2000))),
    on("kubuntu_plasma",()->waitUntilTime(val(2000))),
    on("opensuse_plasma",()->waitUntilTime(val(2000))),
    on("void_i3",()->waitUntilTime(val(2000))),
    on("arch_sway",()->waitUntilTime(val(2000))),
    on("omarchy_hyprland",()->waitUntilTime(val(2000))));
  final Action terminalShown= action("terminalShown",
    on("fedora_cosmic",()->waitUntilTime(val(6500))),
    on("ubuntu_gnome",()->waitUntilTime(val(5500))),
    on("debian_gnome_x11",()->waitUntilTime(val(6500))),
    on("fedora_gnome",()->waitUntilTime(val(6500))),
    on("xubuntu_xfce",()->waitUntilTime(val(6500))),
    on("debian_cinnamon",()->waitUntilTime(val(6500))),
    on("debian_mate",()->waitUntilTime(val(6500))),
    on("lubuntu_lxqt",()->waitUntilTime(val(7000))),
    on("kubuntu_plasma",()->waitUntilTime(val(7000))),
    on("opensuse_plasma",()->waitUntilTime(val(7000))),
    on("void_i3",()->waitUntilTime(val(6500))),
    on("arch_sway",()->waitUntilTime(val(6500))),
    on("omarchy_hyprland",()->waitUntilTime(val(6500))));
  final Action managerShown= action("managerShown",
    on("fedora_cosmic",()->waitUntilTime(val(20000))),
    on("ubuntu_gnome",()->waitUntilTime(val(18500))),
    on("debian_gnome_x11",()->waitUntilTime(val(20000))),
    on("fedora_gnome",()->waitUntilTime(val(20000))),
    on("xubuntu_xfce",()->waitUntilTime(val(20000))),
    on("debian_cinnamon",()->waitUntilTime(val(20000))),
    on("debian_mate",()->waitUntilTime(val(20000))),
    on("lubuntu_lxqt",()->waitUntilTime(val(22500))),
    on("kubuntu_plasma",()->waitUntilTime(val(21000))),
    on("opensuse_plasma",()->waitUntilTime(val(22000))),
    on("void_i3",()->waitUntilTime(val(30000))),
    on("arch_sway",()->waitUntilTime(val(20000))),
    on("omarchy_hyprland",()->waitUntilTime(val(20000))));
  final Action closeInformation= action("closeInformation",
    on("fedora_cosmic",()->click(val(164),val(332))),
    on("ubuntu_gnome",()->click(val(469),val(167))),
    on("debian_gnome_x11",()->click(val(84),val(167))),
    on("fedora_gnome",()->click(val(84),val(167))),
    on("xubuntu_xfce",()->click(val(176),val(288))),
    on("debian_cinnamon",()->click(val(84),val(134))),
    on("debian_mate",()->click(val(163),val(315))),
    on("lubuntu_lxqt",()->click(val(61),val(366))),
    on("kubuntu_plasma",()->click(val(84),val(126))),
    on("opensuse_plasma",()->click(val(84),val(126))),
    on("void_i3",()->click(val(180),val(222))),
    on("arch_sway",()->click(val(180),val(297))),
    on("omarchy_hyprland",()->click(val(338),val(442))),
    on("windows",()->click(val(79),val(120))));
  final Action check= action("check",
    on("fedora_cosmic",()->click(val(204),val(221))),
    on("ubuntu_gnome",()->click(val(483),val(111))),
    on("debian_gnome_x11",()->click(val(102),val(112))),
    on("fedora_gnome",()->click(val(102),val(112))),
    on("xubuntu_xfce",()->click(val(210),val(185))),
    on("debian_cinnamon",()->click(val(102),val(80))),
    on("debian_mate",()->click(val(204),val(204))),
    on("lubuntu_lxqt",()->click(val(76),val(325))),
    on("kubuntu_plasma",()->click(val(102),val(72))),
    on("opensuse_plasma",()->click(val(102),val(72))),
    on("void_i3",()->click(val(214),val(118))),
    on("arch_sway",()->click(val(214),val(193))),
    on("omarchy_hyprland",()->click(val(431),val(243))),
    on("windows",()->click(val(102),val(67))));
  final Action checked= action("checked",
    on("fedora_cosmic",()->waitUntilTime(val(35500))),
    on("ubuntu_gnome",()->waitUntilTime(val(34000))),
    on("debian_gnome_x11",()->waitUntilTime(val(35500))),
    on("fedora_gnome",()->waitUntilTime(val(35500))),
    on("xubuntu_xfce",()->waitUntilTime(val(35500))),
    on("debian_cinnamon",()->waitUntilTime(val(35500))),
    on("debian_mate",()->waitUntilTime(val(35500))),
    on("lubuntu_lxqt",()->waitUntilTime(val(36500))),
    on("kubuntu_plasma",()->waitUntilTime(val(36500))),
    on("opensuse_plasma",()->waitUntilTime(val(37500))),
    on("void_i3",()->waitUntilTime(val(44000))),
    on("arch_sway",()->waitUntilTime(val(34000))),
    on("omarchy_hyprland",()->waitUntilTime(val(34000))));
  final Action checkAgain= action("checkAgain",
    on("fedora_cosmic",()->click(val(204),val(221))),
    on("ubuntu_gnome",()->click(val(483),val(111))),
    on("debian_gnome_x11",()->click(val(102),val(112))),
    on("fedora_gnome",()->click(val(102),val(112))),
    on("xubuntu_xfce",()->click(val(210),val(185))),
    on("debian_cinnamon",()->click(val(102),val(80))),
    on("debian_mate",()->click(val(204),val(204))),
    on("lubuntu_lxqt",()->click(val(76),val(325))),
    on("kubuntu_plasma",()->click(val(102),val(72))),
    on("opensuse_plasma",()->click(val(102),val(72))),
    on("void_i3",()->click(val(214),val(118))),
    on("arch_sway",()->click(val(214),val(193))),
    on("omarchy_hyprland",()->click(val(431),val(243))),
    on("windows",()->click(val(102),val(67))));
  final Action checkedAgain= action("checkedAgain",
    on("fedora_cosmic",()->waitUntilTime(val(49500))),
    on("ubuntu_gnome",()->waitUntilTime(val(48000))),
    on("debian_gnome_x11",()->waitUntilTime(val(49500))),
    on("fedora_gnome",()->waitUntilTime(val(49500))),
    on("xubuntu_xfce",()->waitUntilTime(val(49500))),
    on("debian_cinnamon",()->waitUntilTime(val(49500))),
    on("debian_mate",()->waitUntilTime(val(49500))),
    on("lubuntu_lxqt",()->waitUntilTime(val(50500))),
    on("kubuntu_plasma",()->waitUntilTime(val(50500))),
    on("opensuse_plasma",()->waitUntilTime(val(51500))),
    on("void_i3",()->waitUntilTime(val(58000))),
    on("arch_sway",()->waitUntilTime(val(48000))),
    on("omarchy_hyprland",()->waitUntilTime(val(48000))));
  final Action clearOutput= action("clearOutput",
    on("fedora_cosmic",()->click(val(3728),val(464))),
    on("ubuntu_gnome",()->click(val(3785),val(233))),
    on("debian_gnome_x11",()->click(val(3785),val(233))),
    on("fedora_gnome",()->click(val(3785),val(233))),
    on("xubuntu_xfce",()->click(val(3714),val(412))),
    on("debian_cinnamon",()->click(val(3785),val(200))),
    on("debian_mate",()->click(val(3728),val(447))),
    on("lubuntu_lxqt",()->click(val(3798),val(416))),
    on("kubuntu_plasma",()->click(val(3785),val(192))),
    on("opensuse_plasma",()->click(val(3785),val(192))),
    on("void_i3",()->click(val(3710),val(346))),
    on("arch_sway",()->click(val(3710),val(421))),
    on("omarchy_hyprland",()->click(val(3600),val(682))),
    on("windows",()->click(val(1227),val(184))));
  final Action outputCleared= action("outputCleared",
    on("fedora_cosmic",()->waitUntilTime(val(52000))),
    on("ubuntu_gnome",()->waitUntilTime(val(50500))),
    on("debian_gnome_x11",()->waitUntilTime(val(52000))),
    on("fedora_gnome",()->waitUntilTime(val(52000))),
    on("xubuntu_xfce",()->waitUntilTime(val(52000))),
    on("debian_cinnamon",()->waitUntilTime(val(52000))),
    on("debian_mate",()->waitUntilTime(val(52000))),
    on("lubuntu_lxqt",()->waitUntilTime(val(53000))),
    on("kubuntu_plasma",()->waitUntilTime(val(53000))),
    on("opensuse_plasma",()->waitUntilTime(val(54000))),
    on("void_i3",()->waitUntilTime(val(61000))),
    on("arch_sway",()->waitUntilTime(val(51000))),
    on("omarchy_hyprland",()->waitUntilTime(val(51000))));
  final Action checkAfterClear= action("checkAfterClear",
    on("fedora_cosmic",()->click(val(204),val(221))),
    on("ubuntu_gnome",()->click(val(483),val(111))),
    on("debian_gnome_x11",()->click(val(102),val(112))),
    on("fedora_gnome",()->click(val(102),val(112))),
    on("xubuntu_xfce",()->click(val(210),val(185))),
    on("debian_cinnamon",()->click(val(102),val(80))),
    on("debian_mate",()->click(val(204),val(204))),
    on("lubuntu_lxqt",()->click(val(76),val(325))),
    on("kubuntu_plasma",()->click(val(102),val(72))),
    on("opensuse_plasma",()->click(val(102),val(72))),
    on("void_i3",()->click(val(214),val(118))),
    on("arch_sway",()->click(val(214),val(193))),
    on("omarchy_hyprland",()->click(val(431),val(243))),
    on("windows",()->click(val(102),val(67))));
  final Action checkedAfterClear= action("checkedAfterClear",
    on("fedora_cosmic",()->waitUntilTime(val(66000))),
    on("ubuntu_gnome",()->waitUntilTime(val(64500))),
    on("debian_gnome_x11",()->waitUntilTime(val(66000))),
    on("fedora_gnome",()->waitUntilTime(val(66000))),
    on("xubuntu_xfce",()->waitUntilTime(val(66000))),
    on("debian_cinnamon",()->waitUntilTime(val(66000))),
    on("debian_mate",()->waitUntilTime(val(66000))),
    on("lubuntu_lxqt",()->waitUntilTime(val(67000))),
    on("kubuntu_plasma",()->waitUntilTime(val(67000))),
    on("opensuse_plasma",()->waitUntilTime(val(68000))),
    on("void_i3",()->waitUntilTime(val(75000))),
    on("arch_sway",()->waitUntilTime(val(65000))),
    on("omarchy_hyprland",()->waitUntilTime(val(65000))));
  final Action appsShownToEnd= action("appsShownToEnd",
    on("fedora_cosmic",()->waitUntilTime(val(74000))),
    on("ubuntu_gnome",()->waitUntilTime(val(66000))),
    on("debian_gnome_x11",()->waitUntilTime(val(67500))),
    on("fedora_gnome",()->waitUntilTime(val(74000))),
    on("xubuntu_xfce",()->waitUntilTime(val(67500))),
    on("debian_cinnamon",()->waitUntilTime(val(67500))),
    on("debian_mate",()->waitUntilTime(val(67500))),
    on("lubuntu_lxqt",()->waitUntilTime(val(68500))),
    on("kubuntu_plasma",()->waitUntilTime(val(68500))),
    on("opensuse_plasma",()->waitUntilTime(val(72000))),
    on("void_i3",()->waitUntilTime(val(76500))),
    on("arch_sway",()->waitUntilTime(val(66500))),
    on("omarchy_hyprland",()->waitUntilTime(val(66500))));
  final Action terminalShownToEnd= action("terminalShownToEnd",
    on("fedora_cosmic",()->waitUntilTime(val(80500))),
    on("ubuntu_gnome",()->waitUntilTime(val(69500))),
    on("debian_gnome_x11",()->waitUntilTime(val(72000))),
    on("fedora_gnome",()->waitUntilTime(val(80000))),
    on("xubuntu_xfce",()->waitUntilTime(val(72000))),
    on("debian_cinnamon",()->waitUntilTime(val(72000))),
    on("debian_mate",()->waitUntilTime(val(72000))),
    on("lubuntu_lxqt",()->waitUntilTime(val(73500))),
    on("kubuntu_plasma",()->waitUntilTime(val(73500))),
    on("opensuse_plasma",()->waitUntilTime(val(78000))),
    on("void_i3",()->waitUntilTime(val(83000))),
    on("arch_sway",()->waitUntilTime(val(71000))),
    on("omarchy_hyprland",()->waitUntilTime(val(71000))));
  final Action managerEnded= action("managerEnded",
    on("fedora_cosmic",()->waitUntilTime(val(92000))),
    on("ubuntu_gnome",()->waitUntilTime(val(79500))),
    on("debian_gnome_x11",()->waitUntilTime(val(82000))),
    on("fedora_gnome",()->waitUntilTime(val(92000))),
    on("xubuntu_xfce",()->waitUntilTime(val(82000))),
    on("debian_cinnamon",()->waitUntilTime(val(82000))),
    on("debian_mate",()->waitUntilTime(val(82000))),
    on("lubuntu_lxqt",()->waitUntilTime(val(84000))),
    on("kubuntu_plasma",()->waitUntilTime(val(84000))),
    on("opensuse_plasma",()->waitUntilTime(val(90000))),
    on("void_i3",()->waitUntilTime(val(93000))),
    on("arch_sway",()->waitUntilTime(val(83000))),
    on("omarchy_hyprland",()->waitUntilTime(val(83000))));
  @Override void walk() throws Throwable{
    noManagerData();
    var project= project("helloWorld");
    var console= List.of(data,"eclipse","hello_world","console.txt");
    var ok= "--- ok: no problem found ---\n";
    launchScript("first",project);
    runInTerminal(appsShown,terminalShown);
    managerShown.go();
    closeInformation.go();
    stabilize();
    checkContent(console,"");
    check.go();
    checked.go();
    stabilize();
    checkContent(console,ok);
    checkAgain.go();
    checkedAgain.go();
    stabilize();
    checkContent(console,ok+ok);
    clearOutput.go();
    outputCleared.go();
    stabilize();
    checkContent(console,"");
    checkAfterClear.go();
    checkedAfterClear.go();
    stabilize();
    checkContent(console,ok);
    endScript();
    runInTerminal(appsShownToEnd,terminalShownToEnd);
    managerEnded.go();
    stabilize();
    checkContent(List.of("first.exit"),"137\n");
  }
}
